// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAieNzAxrwyd8KPexsodB0ICoVTMIhOMyU',
    appId: '1:637656509591:web:c561828ce392873bd08dd2',
    messagingSenderId: '637656509591',
    projectId: 'albazar-c3f51',
    authDomain: 'albazar-c3f51.firebaseapp.com',
    storageBucket: 'albazar-c3f51.firebasestorage.app',
    measurementId: 'G-XY7BKX6VF3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBj19UwVvRq3mDM02sASmyKCudBXkdmJ3o',
    appId: '1:637656509591:android:f34d103375e8372bd08dd2',
    messagingSenderId: '637656509591',
    projectId: 'albazar-c3f51',
    storageBucket: 'albazar-c3f51.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD7CBxtPg_X46fPl438z0rL7IRoyeYQUUM',
    appId: '1:637656509591:ios:60e86122a87cf7aad08dd2',
    messagingSenderId: '637656509591',
    projectId: 'albazar-c3f51',
    storageBucket: 'albazar-c3f51.firebasestorage.app',
    iosBundleId: 'com.example.albazarApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD7CBxtPg_X46fPl438z0rL7IRoyeYQUUM',
    appId: '1:637656509591:ios:60e86122a87cf7aad08dd2',
    messagingSenderId: '637656509591',
    projectId: 'albazar-c3f51',
    storageBucket: 'albazar-c3f51.firebasestorage.app',
    iosBundleId: 'com.example.albazarApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAieNzAxrwyd8KPexsodB0ICoVTMIhOMyU',
    appId: '1:637656509591:web:7621aff50b7cd8e7d08dd2',
    messagingSenderId: '637656509591',
    projectId: 'albazar-c3f51',
    authDomain: 'albazar-c3f51.firebaseapp.com',
    storageBucket: 'albazar-c3f51.firebasestorage.app',
    measurementId: 'G-4WNX2DLEDC',
  );
}
